UPSERT products:u'018f1000-0000-7000-8000-000000001001' CONTENT {
    name: "Стеклянная ваза",
    marker: [{ Weak: {} }],
    bounds: { width: 20, height: 30, depth: 20 },
    weight: 1000,
    count: 20,
    volume: 12000
};

UPSERT products:u'018f1000-0000-7000-8000-000000001002' CONTENT {
    name: "Книга",
    marker: NONE,
    bounds: { width: 21, height: 29, depth: 4 },
    weight: 700,
    count: 100,
    volume: 2436
};

UPSERT products:u'018f1000-0000-7000-8000-000000001003' CONTENT {
    name: "Керамическая кружка",
    marker: [{ Weak: {} }],
    bounds: { width: 12, height: 10, depth: 10 },
    weight: 350,
    count: 50,
    volume: 1200
};

UPSERT products:u'018f1000-0000-7000-8000-000000001004' CONTENT {
    name: "Пауэрбанк",
    marker: [{ Fire: {} }, { Water: {} }],
    bounds: { width: 15, height: 3, depth: 7 },
    weight: 250,
    count: 30,
    volume: 315
};
